# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dc7ce3bfd6e72a59c56732d382cd65fe"
name = "Avada First App"
application_url = "https://arabia-thus-trainers-sports.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_order_edits,read_order_edits,read_orders,write_orders,read_product_feeds,write_product_feeds,read_product_listings,write_product_listings,read_products,write_products,read_script_tags,write_script_tags,write_theme_code,read_themes,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
